language: php

os: linux

dist: xenial

git:
  depth: 3

php:
  - '7.4.1'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./bin/phpunit --testsuite unit --coverage-clover coverage.xml

env:
  - CODECOV_TOKEN="ce5e213b-e934-429c-b91e-c533a9b6f632"

after_success:
  - bash <(curl -s https://codecov.io/bash) -f $TRAVIS_BUILD_DIR/coverage.xml

